---
dependencies: []
galaxy_info:
  author: SummitEthic
  description: Common role for base system configuration
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
