---
- name: Update and upgrade the system
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
  register: system_update
  notify: "Reboot if needed"
  tags: [bootstrap]

- name: Include user creation tasks
  ansible.builtin.include_tasks: user_creation.yml
  tags: [bootstrap, user_creation]
