---
- name: Template Mailcow environment configuration
  ansible.builtin.template:
    src: templates/mailcow.env.j2
    dest: "{{ mailcow_dest }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags: [mailcow, template]

- name: Allow mail-related ports in UFW (Debian-based systems)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ mailcow_ports }}"
  become: true
  when: ansible_facts['os_family'] == 'Debian'
  tags: [mailcow, ufw]

- name: Create Docker Compose override for Traefik integration
  ansible.builtin.copy:
    dest: "{{ mailcow_dest }}/docker-compose.override.yml"
    content: |
      services:
        nginx-mailcow:
          ports: []
          volumes:
            - /etc/ssl/mail:/etc/ssl/mail:ro
          networks:
            - mailcow-network
            - traefik-public
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mailcow.rule=Host(`{{ mailcow_hostname }}`)"
            - "traefik.http.routers.mailcow.entrypoints=websecure"
            - "traefik.http.routers.mailcow.tls.certresolver=myresolver"
            - "traefik.http.routers.mailcow-http.rule=Host(`{{ mailcow_hostname }}`)"
            - "traefik.http.routers.mailcow-http.entrypoints=web"
            - "traefik.http.routers.mailcow-http.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.services.mailcow.loadbalancer.server.port=8080"
      networks:
        traefik-public:
          external: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: true
  tags: [mailcow, docker, traefik]
