---
- name: Template Mailcow environment configuration
  ansible.builtin.template:
    src: templates/mailcow.env.j2
    dest: "{{ mailcow_dest }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags: [mailcow, template]

- name: Allow mail-related ports in UFW (Debian-based systems)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ mailcow_ports }}"
  become: true
  when: ansible_facts['os_family'] == 'Debian'
  tags: [mailcow, ufw]

- name: Create Dovecot configuration directories
  ansible.builtin.file:
    path: "{{ mailcow_dest }}/data/conf/dovecot/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - ""
    - "extra"
  tags: [mailcow, fix]

- name: Copy custom Dovecot configuration
  ansible.builtin.copy:
    dest: "{{ mailcow_dest }}/data/conf/dovecot/extra/disable-fts.conf"
    content: |
      # Explicitly disable FTS to avoid the problematic sed command
      mail_plugins = $mail_plugins quota imap_quota notify push_notification
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags: [mailcow, fix]

- name: Create Docker Compose override for integration
  ansible.builtin.template:
    src: templates/docker-compose.override.yml.j2
    dest: "{{ mailcow_dest }}/docker-compose.override.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags: [mailcow, docker, traefik]
