---
- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml
  tags: [mailcow, install]

- name: Include certificates tasks
  ansible.builtin.include_tasks: certificates.yml
  tags: [mailcow, certificates]

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags: [mailcow, configure]

- name: Create or ensure Mailcow network exists
  community.docker.docker_network:
    name: mailcow-network
    driver: bridge
    state: present
  become: true
  tags: [mailcow, docker]

- name: Deploy Mailcow using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ mailcow_dest }}"
    state: present
    pull: always
  become: true
  tags: [mailcow, docker]
