---
- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml
  tags: [mailcow, install]

- name: Include certificates tasks
  ansible.builtin.include_tasks: certificates.yml
  tags: [mailcow, certificates]

- name: Include SSL parameters generation
  ansible.builtin.include_tasks: ssl-params.yml
  tags: [mailcow, ssl]

- name: Include dovecot fix tasks
  ansible.builtin.include_tasks: fix-dovecot.yml
  tags: [mailcow, fix]

- name: Include fail2ban configuration
  ansible.builtin.include_tasks: fail2ban.yml
  tags: [mailcow, fail2ban]

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags: [mailcow, configure]

- name: Create or ensure Mailcow network exists
  community.docker.docker_network:
    name: mailcow-network
    driver: bridge
    state: present
  become: true
  tags: [mailcow, docker]

- name: Include restart tasks
  ansible.builtin.include_tasks: restart.yml
  tags: [mailcow, restart]
