---
dependencies: []
galaxy_info:
  author: SummitEthic
  description: Role for security hardening, UFW and Fail2Ban configuration, Docker installation, and swap file management.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
