---
- name: Create Traefik directory
  ansible.builtin.file:
    path: /opt/traefik
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  tags: [traefik, directory]

- name: Template Traefik docker-compose file
  ansible.builtin.template:
    src: templates/traefik-docker-compose.yml.j2
    dest: /opt/traefik/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags: [traefik, template]

- name: Create Traefik public network
  community.docker.docker_network:
    name: "{{ traefik_public_network }}"
    driver: bridge
    state: present
  tags: [traefik, docker]

- name: Deploy Traefik using Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: present
    pull: always
  become: true
  tags: [traefik, docker]
