---
- name: Ensure docker-compose-plugin is installed
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
    update_cache: true
  tags: [traefik, prerequisites]

- name: Install Python requests library
  ansible.builtin.apt:
    name: python3-requests
    state: present
    update_cache: true
  become: true
  tags: [traefik, prerequisites]

- name: Include deployment tasks
  ansible.builtin.include_tasks: deploy.yml
  tags: [traefik, deploy]
