---
- name: "Deploy Applications"
  hosts: all
  remote_user: "{{ ansible_user }}"
  gather_facts: true
  become: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/vault.yml"
  tags:
    - deploy
  roles:
    - traefik
    - mailcow
